name = "proposalkit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "63703d23e89f4b7dbd1d80337cbff6a1"
preview_id = "50608aa3b884483595d1f1224430a7bb"
