import { Metadata } from "next";
import Link from "next/link";
import ThemeToggle from "@/components/ThemeToggle";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your use of ProposalKit, including free-tier limits, acceptable use, intellectual property, and dispute resolution.",
};

export default function TermsPage() {
  return (
    <>
      <header className="nav">
        <Link className="logo" href="/">
          <span className="logo-mark" style={{ color: "#2563EB" }}>
            <svg viewBox="0 0 20 20" width="18" height="18" fill="none">
              <rect x="2" y="2" width="16" height="16" rx="4" fill="currentColor" />
              <path
                d="M7 6.5h4.2a2.3 2.3 0 010 4.6H7V6.5zM7 11.1V14"
                stroke="white"
                strokeWidth="1.6"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </span>
          <span className="logo-word">ProposalKit</span>
        </Link>
        <nav className="nav-links">
          <Link href="/about">About</Link>
          <Link href="/guides">Guides</Link>
          <ThemeToggle />
          <Link className="btn btn-primary btn-sm" href="/" style={{ background: "#2563EB" }}>
            Try free
          </Link>
        </nav>
      </header>
      <div className="page">
        <article className="doc">
          <header className="doc-head">
            <h1>Terms of Service</h1>
            <p className="meta">Last updated: April 2026</p>
          </header>

          <p>
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of ProposalKit
            (the &quot;Service&quot;), operated at proposalkit.pages.dev. By accessing or using the
            Service, you agree to be bound by these Terms and our{" "}
            <Link href="/privacy">Privacy Policy</Link>. If you do not agree, please discontinue use
            of the Service. These Terms constitute a legally binding agreement between you and the
            operators of ProposalKit.
          </p>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By creating an account, signing in with Google, or otherwise accessing the Service —
              including as a guest user without an account — you represent and warrant that: (a)
              you are at least 16 years of age (or the age of majority in your jurisdiction, if
              higher); (b) you have the legal capacity to enter into these Terms; (c) if you are
              accessing the Service on behalf of an organization, you have authority to bind that
              organization to these Terms; and (d) your use of the Service will comply with these
              Terms and all applicable laws and regulations.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              ProposalKit is an AI-assisted document drafting tool that helps small business
              owners, freelancers, and service professionals generate business proposal drafts. You
              submit a small number of inputs (industry, client name, scope of work, budget,
              optional timeline and business name), and the Service produces a structured proposal
              draft using a third-party large language model (currently Google Gemini 2.5 Flash).
            </p>
            <p>
              The Service is provided as a tool to assist your work. The proposals generated by
              the Service are drafts that you are expected to review, edit, and adapt before
              sending to clients. The Service is not a substitute for professional legal, financial,
              or business advice, and the AI-generated content does not constitute a legally
              binding contract until you have reviewed, customized, and executed it through your
              own agreement process.
            </p>
          </section>

          <section>
            <h2>3. Eligibility and Account Registration</h2>
            <p>
              You may use the Service as a guest without registering, subject to the guest usage
              limits described below. To access the registered-user features, you must sign in with
              a valid Google account. By signing in, you authorize us to receive your basic profile
              information from Google in accordance with our{" "}
              <Link href="/privacy">Privacy Policy</Link>.
            </p>
            <p>
              You are responsible for maintaining the security of your Google account and for all
              activities that occur under your account. You must notify us immediately of any
              unauthorized access. We are not liable for any loss or damage arising from your
              failure to safeguard your credentials.
            </p>
          </section>

          <section>
            <h2>4. Free Tier and Usage Limits</h2>
            <p>The Service is offered in two free tiers:</p>
            <ul>
              <li>
                <strong>Guest users.</strong> One proposal generation per browser session. Guest
                usage is tracked via session storage and resets when you close the tab. Guests do
                not have an account and cannot save or retrieve previous proposals beyond the
                current browser session.
              </li>
              <li>
                <strong>Registered users.</strong> Up to five (5) proposals per calendar month per
                user account. Counts reset at 00:00 UTC on the 1st of each month. Once you reach
                the limit, you must wait until the reset or upgrade to a paid plan (when available).
              </li>
              <li>
                <strong>Paid plan.</strong> Unlimited generation and additional features. The paid
                tier is on the roadmap but not yet launched. Pricing and feature details will be
                published before launch.
              </li>
            </ul>
            <p>
              We reserve the right to modify the free-tier limits, introduce new pricing tiers,
              or adjust the features available to each tier. We will provide registered users with
              advance notice via email for material changes.
            </p>
          </section>

          <section>
            <h2>5. Acceptable Use Policy</h2>
            <p>
              You agree to use the Service only for lawful purposes and in a way that does not
              infringe the rights of, restrict, or inhibit anyone else&apos;s use of the Service.
              Without limiting the foregoing, you agree NOT to:
            </p>
            <ul>
              <li>
                Generate proposals containing fraudulent, deceptive, misleading, or false
                statements; including misrepresenting your identity, qualifications, services, or
                pricing.
              </li>
              <li>
                Use the Service to draft contracts or proposals intended to defraud, harm, or
                deceive recipients, or to facilitate illegal activity of any kind.
              </li>
              <li>
                Use automation, bots, scripts, multiple accounts, or any other means to circumvent
                rate limits, usage caps, or other restrictions.
              </li>
              <li>
                Attempt to disrupt, overload, or impair the Service through denial-of-service
                attacks, automated probing, or excessive traffic.
              </li>
              <li>
                Reverse engineer, decompile, or attempt to derive the source code of the Service,
                except where such activity is permitted by applicable law.
              </li>
              <li>
                Probe the Service for security vulnerabilities outside the coordinated disclosure
                process described at{" "}
                <a href="mailto:security@proposalkit.app">security@proposalkit.app</a>.
              </li>
              <li>
                Use the Service to generate content that is illegal, harmful, abusive, harassing,
                defamatory, obscene, or that violates the rights of third parties (including
                intellectual property, privacy, or publicity rights).
              </li>
              <li>
                Resell, sublicense, or commercially redistribute the Service or its output as a
                competing product.
              </li>
              <li>
                Use the Service in a way that violates any applicable law, regulation, or industry
                standard, including but not limited to consumer protection laws, advertising
                regulations, and professional licensing requirements.
              </li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these rules. In
              cases of severe or repeated violations, we may also report illegal activity to
              relevant authorities.
            </p>
          </section>

          <section>
            <h2>6. Intellectual Property Rights</h2>
            <h3>Your content and generated proposals</h3>
            <p>
              You retain all rights to the inputs you submit (client names, scopes of work, budgets,
              and any other information you provide). The proposals generated by the Service based
              on your inputs are yours to use, edit, distribute, and send to clients without
              attribution or royalty. We do not claim ownership over the proposals you generate.
            </p>
            <h3>The Service itself</h3>
            <p>
              The Service, including the website, the underlying software, the brand and logos, the
              user interface, the documentation, and all other materials provided by ProposalKit,
              are owned by us or our licensors and are protected by copyright, trademark, and other
              intellectual property laws. You may not copy, modify, distribute, sell, or lease any
              part of the Service or its source code. You may not rebrand, white-label, or
              resell the Service as your own.
            </p>
            <h3>Feedback you submit</h3>
            <p>
              If you provide feedback, suggestions, or ideas about the Service, you grant us a
              perpetual, worldwide, royalty-free license to use, modify, and incorporate that
              feedback into the Service or any future products without obligation to compensate or
              credit you.
            </p>
          </section>

          <section>
            <h2>7. AI-Generated Content and Accuracy</h2>
            <p>
              The Service uses third-party AI models to generate proposal drafts. AI-generated
              content may contain errors, omissions, inaccuracies, outdated information, or
              statements that do not reflect best practices for your industry or jurisdiction.
              <strong>
                {" "}
                You are responsible for reviewing all AI-generated content for accuracy,
                appropriateness, and legal compliance before sending it to clients or using it for
                business purposes.
              </strong>
            </p>
            <p>
              ProposalKit makes no representations or warranties that the generated content is
              suitable for any particular purpose, complies with any specific legal or regulatory
              requirements, or will produce any specific business outcome. We are not liable for
              any losses, damages, or claims arising from your use of AI-generated content,
              including but not limited to lost business, contractual disputes, regulatory
              penalties, or reputational harm.
            </p>
          </section>

          <section>
            <h2>8. Third-Party Services</h2>
            <p>
              The Service relies on third-party providers including Google (Gemini API and OAuth
              sign-in), Cloudflare (hosting and KV storage), and Resend (email delivery). Your use
              of the Service is also subject to the terms and policies of these third parties. We
              are not responsible for the actions or omissions of third-party providers, including
              service outages, data breaches, or changes to their terms.
            </p>
          </section>

          <section>
            <h2>9. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
              WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. TO THE FULLEST EXTENT
              PERMITTED BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO
              WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
              ACCURACY, RELIABILITY, AND UNINTERRUPTED OPERATION. WE DO NOT WARRANT THAT THE SERVICE
              WILL BE ERROR-FREE, SECURE, OR AVAILABLE AT ALL TIMES.
            </p>
          </section>

          <section>
            <h2>10. Limitation of Liability</h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PROPOSALKIT, ITS
              OPERATORS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES — INCLUDING LOST PROFITS, LOST BUSINESS, LOST DATA,
              OR REPUTATIONAL HARM — ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, EVEN IF
              WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL CUMULATIVE
              LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM YOUR USE OF THE SERVICE SHALL NOT EXCEED
              ONE HUNDRED US DOLLARS ($100), OR THE AMOUNT YOU HAVE PAID US IN THE TWELVE MONTHS
              PRECEDING THE CLAIM, WHICHEVER IS GREATER.
            </p>
          </section>

          <section>
            <h2>11. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless ProposalKit and its operators,
              affiliates, employees, and contractors from and against any claims, damages,
              liabilities, losses, and expenses (including reasonable attorneys&apos; fees) arising
              from: (a) your use of the Service; (b) your violation of these Terms; (c) your
              violation of any third-party rights, including intellectual property or privacy
              rights; or (d) your use of AI-generated content in your business activities.
            </p>
          </section>

          <section>
            <h2>12. Termination</h2>
            <p>
              You may stop using the Service at any time. You may request deletion of your account
              by emailing{" "}
              <a href="mailto:privacy@proposalkit.app">privacy@proposalkit.app</a>; we will process
              verified requests within 30 days.
            </p>
            <p>
              We may suspend or terminate your access to the Service at any time, with or without
              notice, for any reason, including but not limited to: violation of these Terms,
              suspected fraud or abuse, legal or regulatory obligations, or discontinuation of the
              Service. Upon termination, your right to use the Service ceases immediately. The
              provisions of these Terms that by their nature should survive termination
              (intellectual property, disclaimers, limitations of liability, indemnification,
              dispute resolution) shall survive.
            </p>
          </section>

          <section>
            <h2>13. Governing Law and Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              Republic of Korea, without regard to its conflict-of-law principles. Any disputes
              arising out of or related to these Terms or the Service shall be resolved through
              good-faith negotiation between the parties. If negotiation fails, disputes shall be
              submitted to the exclusive jurisdiction of the courts located in Seoul, Republic of
              Korea.
            </p>
            <p>
              Nothing in these Terms prevents you from raising consumer-protection claims with the
              applicable regulatory authority in your jurisdiction, or from exercising mandatory
              rights granted to you by your local law that cannot be waived by contract.
            </p>
          </section>

          <section>
            <h2>14. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. When we make material changes, we will
              update the &quot;Last updated&quot; date at the top of this page and, for registered
              users, send email notification at least 14 days before the changes take effect.
              Continued use of the Service after the effective date of the changes constitutes your
              acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2>15. Severability and Entire Agreement</h2>
            <p>
              If any provision of these Terms is held to be unenforceable, the remaining provisions
              shall continue in full force and effect. These Terms, together with our{" "}
              <Link href="/privacy">Privacy Policy</Link>, constitute the entire agreement between
              you and ProposalKit regarding the Service, and supersede any prior agreements or
              understandings.
            </p>
          </section>

          <section>
            <h2>16. Contact</h2>
            <p>
              Questions about these Terms? Email{" "}
              <a href="mailto:hello@proposalkit.app">hello@proposalkit.app</a> or see our{" "}
              <Link href="/contact">contact page</Link>.
            </p>
          </section>
        </article>

        <footer className="footer">
          <span>© 2026 ProposalKit. All rights reserved.</span>
          <nav>
            <Link href="/about">About</Link>
            <span className="sep">·</span>
            <Link href="/guides">Guides</Link>
            <span className="sep">·</span>
            <Link href="/contact">Contact</Link>
            <span className="sep">·</span>
            <Link href="/privacy">Privacy Policy</Link>
            <span className="sep">·</span>
            <Link href="/terms">Terms of Service</Link>
          </nav>
        </footer>
      </div>
    </>
  );
}
